from typing import TypedDict, List , Optional
from langgraph.graph import StateGraph, END
import cv2
import numpy as np
from ultralytics import YOLO
import base64
# from IPython.display import Image, display
import requests # Swapped to requests for simpler synchronous execution
# import easyocr

# reader = easyocr.Reader(['en'], gpu=False)

server_model = YOLO("./models/epoch90.pt")
license_model=YOLO("./models/license-plate-finetune-v1l.pt")
face_model=YOLO("./models/yolov8m-face-lindevs.pt")

class IncidentState(TypedDict):
    # Data incoming from Edge (YOLO26n)
    img_id: str
    camera_id: str
    timestamp: str
    geolocation: dict # {'lat': 8.5, 'lon': 76.9}
    frame: bytes      # The actual image data
    
    # Data to be generated by Server (epoch90.pt)
    hazards: List[str]     # ['fire', 'injury', 'major']
    severity: str          # 'critical', 'medium', 'low'
    
    nearest_station: str
    status: str   # 'Received', 'Analyzed', 'Reported', 'Failed'
    license_plates: Optional[List[bytes]]
    detected_faces:Optional[List[bytes]]
    plate_num: Optional[List[str]]       

def initialize_incident(state: IncidentState):
    """Validates the incoming data and sets the initial status."""
    print(f"\n--- [START] Processing Event: {state['img_id']} ---")
    print(f"📍 Location: {state['geolocation']}")
    return {"status": "Received"}

def run_epoch90_analysis(state: IncidentState):
    """Runs the high-accuracy multiclass model on the frame sent from edge."""
    
    # Decode bytes to image
    nparr = np.frombuffer(state['frame'], np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    
    # Validate decoded image
    if img is None:
        print("❌ ERROR: cv2.imdecode failed — frame bytes are invalid or corrupted")
        return {"hazards": [], "status": "Failed"}
    
    print(f"✅ Image decoded successfully: shape={img.shape}, dtype={img.dtype}")
    print(f"🔧 Model classes available: {server_model.names}")
    
    # Run inference
    results = server_model(img, conf=0.25, verbose=True)
    
    print("-------------------results---------------------------")
    print(f"Number of boxes detected: {len(results[0].boxes)}")
    print(f"Raw boxes: {results[0].boxes}")
    print("-----------------------end---------------------------")
    
    # Parse detections
    found_hazards = []
    for box in results[0].boxes:
        cls_id = int(box.cls[0])
        confidence = float(box.conf[0])
        label = server_model.names[cls_id].lower()
        print(f"   Detected: {label} (conf={confidence:.2f})")
        found_hazards.append(label)
    
    unique_hazards = list(set(found_hazards))
    print("------------------------------------------------")
    print(unique_hazards)
    print("------------------------------------------------")
    
    if not unique_hazards:
        print("⚠️ No hazards detected above confidence threshold.")
    else:
        print(f"🔍 Server Analysis Complete: {unique_hazards}")
    
    return {
        "hazards": unique_hazards,
        "status": "Analyzed"
    }

def server2_analysis(state: IncidentState):
    """Runs the high-accuracy multiclass model on the frame sent from edge."""
    if len(state["hazards"]) > 0:
        print(f"⏭️ [NODE: DISPATCH] Event hazard node already updated-------------------")
        return {"status": "hazard identified proceed"}
    # Decode bytes to image
    nparr = np.frombuffer(state['frame'], np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    
    # Validate decoded image
    if img is None:
        print("❌ ERROR: cv2.imdecode failed — frame bytes are invalid or corrupted")
        return {"hazards": [], "status": "Failed"}
    
    print(f"✅ Image decoded successfully: shape={img.shape}, dtype={img.dtype}")
    print(f"🔧 Model classes available: {server_model.names}")
    
    # Run inference
    results = server_model(img, conf=0.25, verbose=True)
    
    print("-------------------results---------------------------")
    print(f"Number of boxes detected: {len(results[0].boxes)}")
    print(f"Raw boxes: {results[0].boxes}")
    print("-----------------------end---------------------------")
    
    # Parse detections
    found_hazards = []
    for box in results[0].boxes:
        cls_id = int(box.cls[0])
        confidence = float(box.conf[0])
        label = server_model.names[cls_id].lower()
        print(f"   Detected: {label} (conf={confidence:.2f})")
        found_hazards.append(label)
    
    unique_hazards = list(set(found_hazards))
    print("------------------------------------------------")
    print(unique_hazards)
    print("------------------------------------------------")
    
    if not unique_hazards:
        print("⚠️ No hazards detected above confidence threshold.")
    else:
        print(f"🔍 Server Analysis Complete: {unique_hazards}")
    
    return {
        "hazards": unique_hazards,
        "status": "Analyzed"
    }

def update_service_node(state: IncidentState):
    """
    Determines which emergency services to notify based on YOLO analysis.
    Logic: 
    - Fire detected -> Add Fire + Police
    - High/Medium/Severe -> Add Police (and potentially Medical)
    """
    print(f"📡 [NODE: SERVICE_ROUTING] Evaluating responders for {state['img_id']}...")
    
    # We'll use a set to avoid duplicate services
    services_to_alert = set()
    hazards = state.get("hazards", [])
    severity = state.get("severity", "Low").lower()

    # 1. THE FIRE RULE
    if "fire" in hazards or "smoke" in hazards:
        services_to_alert.add("Fire Department")
        services_to_alert.add("Police") # Always alert police for fire-related traffic stops

    # 2. THE SEVERITY RULE
    # If it's High, Severe, or Critical, we need Medical and Police
    if any(s in severity for s in ["high", "severe", "critical", "major"]):
        services_to_alert.add("Ambulance/Medical")
        services_to_alert.add("Police")
    
    # 3. THE DEFAULT RULE
    # If a hazard was detected at all, at least the Police should be notified
    if len(hazards) > 0 and not services_to_alert:
        services_to_alert.add("Police")

    # Convert back to a string or list for the state
    service_list = ", ".join(list(services_to_alert)) if services_to_alert else "None (Monitor Only)"
    
    print(f"🚑 Dispatching: {service_list}")
    
    return {
        "nearest_station": service_list,
        "status": "Responders_Identified"
    }
    
# def license_plate_node(state: IncidentState):
#     """
#     Finds license plate crops from YOLO results and decrypts them using EasyOCR.
#     """
#     print(f"🕵️ [NODE: OCR] Attempting to decrypt plates for {state['img_id']}...")
    
#     # 1. Decode the frame
#     nparr = np.frombuffer(state['frame'], np.uint8)
#     img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    
#     # 2. Run your license-plate YOLO model (assuming it's loaded as lp_model)
#     # If you are using the same server_model, it must have a 'license-plate' class
#     lp_results = server_model(img, conf=0.40, verbose=False)
    
#     detected_plate_text = "Not Found"

#     # 3. Process the crops
#     for result in lp_results:
#         for box in result.boxes:
#             label = server_model.names[int(box.cls[0])].lower()
            
#             if "license" in label or "plate" in label:
#                 # Get coordinates for the crop
#                 x1, y1, x2, y2 = map(int, box.xyxy[0])
                
#                 # CROP the image using NumPy slicing
#                 plate_crop = img[y1:y2, x1:x2]
                
#                 # 4. DECRYPT with EasyOCR
#                 # detail=0 returns just the text strings
#                 ocr_results = reader.readtext(plate_crop, detail=0)
                
#                 if ocr_results:
#                     # Clean the text (remove spaces/special chars)
#                     detected_plate_text = "".join(ocr_results).upper().replace(" ", "")
#                     print(f"🆔 PLATE DECRYPTED: {detected_plate_text}")
#                     break # Stop after finding the first clear plate

#     return {
#         "plate_number": detected_plate_text,
#     }
# CHANGED: Made synchronous and fixed dictionary keys
def node_api_dispatch(state: IncidentState):
    """Final node in the graph. Sends the completed AI analysis to the external FastAPI Dashboard."""


    if not state.get("hazards") or len(state["hazards"]) == 0:
        print(f"⏭️ [NODE: DISPATCH] Event {state['img_id']} was a False Alarm. Skipping Dispatch.")
        return {"status": "Ignored_False_Alarm"}
    print(f"🌐 [NODE: DISPATCH] Sending Event {state['img_id']} to Dashboard...")
    
    def b64_encoder(byte_list):
        if not byte_list: return []
        return [base64.b64encode(b).decode('utf-8') for b in byte_list if b]

    # 3. Encoding Plates and Faces separately
    # Even though they both use the same helper, we keep them in different variables
    encoded_plates = b64_encoder(state.get("license_plates", []))
    encoded_faces = b64_encoder(state.get("detected_faces", []))

    # Change this to your actual running FastAPI URL later
    DASHBOARD_API_URL = "http://127.0.0.1:8000/api/v1/incidents"
    
    # Aligning the payload with your IncidentState keys
    payload = {
        "event_id": state["img_id"],
        "timestamp": state["timestamp"],
        "location": state["geolocation"],
        "license_plates":encoded_plates,
        "detected_faces":encoded_faces,
        "analysis": {
            "hazards": state["hazards"],
            "severity": state.get("severity", "Unknown")
        },
        "routing": {
            "services": state.get("nearest_station", "Pending Dispatch")
        }
    }
    
    try:
        # Using requests.post for clean synchronous execution
        response = requests.post(
            DASHBOARD_API_URL, 
            json=payload,
            timeout=5.0,
            headers={"X-API-Key": "your_secure_hackathon_key"}
        )
        response.raise_for_status()
        print("✅ [NODE: DISPATCH] Dashboard successfully updated.")
        return {"status": "Reported"}
        
    except requests.exceptions.RequestException as e:
        # This will trigger right now because your FastAPI server isn't running yet!
        print(f"⚠️ [NODE: DISPATCH] Could not reach dashboard API: {e}")
        return {"status": "API_Failed"}

def plate_crop_node(state: IncidentState):
    """
    Detects ALL license plates in the frame, crops them, 
    and saves them as an Optional List of bytes in the state.
    """
    # 1. Guard Clause: Don't process if no accident was found
    if not state.get("hazards") or len(state["hazards"]) == 0:
        print("⏭️ [NODE: CROP] No hazards found. Skipping plate extraction.")
        # We return an empty list to keep the state type consistent
        return {"license_plates": [], "status": "Skipped_No_Hazards"}

    print(f"✂️ [NODE: CROP] Extracting all plates for {state['img_id']}...")

    # 2. Decode the frame from state bytes
    nparr = np.frombuffer(state['frame'], np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    if img is None:
        print("❌ [NODE: CROP] Decoding failed.")
        return {"status": "Error: Decoding Failed"}

    # 3. Run Inference
    results = license_model.predict(source=img, save=False, conf=0.25, verbose=False)

    # 4. Process ALL detected plates into a list
    all_plate_crops = []
    
    # Get image dimensions for safe cropping
    h, w = img.shape[:2]

    for result in results:
        # Loop through every detected box (multiple vehicles)
        for box in result.boxes:
            # Extract coordinates
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            # Safety check: Ensure coordinates are within the image frame
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(w, x2), min(h, y2)

            # --- CROP ---
            cropped_plate = img[y1:y2, x1:x2]
            
            # Skip if the crop is empty/invalid
            if cropped_plate.size == 0:
                continue

            # --- CONVERT TO BYTES ---
            success, buffer = cv2.imencode('.png', cropped_plate)
            if success:
                all_plate_crops.append(buffer.tobytes())

    # 5. Update the State
    print(f"✅ Successfully cropped {len(all_plate_crops)} license plates.")
    
    return {
        "license_plates": all_plate_crops, 
    }
   
    
    
def face_crop_node(state: IncidentState):
    """
    Detects ALL faces in the frame, crops them, 
    and saves them as an Optional List of bytes.
    """
    # 1. Guard Clause: Skip if no hazard (saves server compute)
    if not state.get("hazards"):
        return {"detected_faces": [], "status": "Skipped_No_Hazards"}

    print(f"👤 [NODE: FACE_CROP] Extracting faces for {state['img_id']}...")

    # 2. Decode the frame
    nparr = np.frombuffer(state['frame'], np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    if img is None: return {"status": "Error: Decoding Failed"}

    # 3. Run Face Detection Model
    # Ensure face_model is loaded globally: face_model = YOLO("yolov11n-face.pt")
    results = face_model.predict(source=img, save=False, conf=0.30, verbose=False)

    all_face_crops = []
    h, w = img.shape[:2]

    for result in results:
        for box in result.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            # Safety Clipping
            x1, y1, x2, y2 = max(0, x1), max(0, y1), min(w, x2), min(h, y2)

            # --- CROP ---
            face_crop = img[y1:y2, x1:x2]
            
            if face_crop.size == 0: continue

            # --- CONVERT TO BYTES ---
            success, buffer = cv2.imencode('.png', face_crop)
            if success:
                all_face_crops.append(buffer.tobytes())

    print(f"✅ Successfully cropped {len(all_face_crops)} faces.")
    
    return {
        "detected_faces": all_face_crops, 
    }



# ==========================================
# GRAPH COMPILATION
# ==========================================
workflow = StateGraph(IncidentState)

# CHANGED: Added the dispatch node
workflow.add_node("init", initialize_incident)
workflow.add_node("analyze", run_epoch90_analysis)
workflow.add_node("server2",server2_analysis)
workflow.add_node("dispatch", node_api_dispatch) 
workflow.add_node("service_identify",update_service_node)
workflow.add_node("license_node",plate_crop_node)
workflow.add_node("face",face_crop_node)

# CHANGED: Updated the edges to flow through the new node
workflow.set_entry_point("init")
workflow.add_edge("init", "analyze")
workflow.add_edge("analyze","server2")
workflow.add_edge("server2","license_node")
workflow.add_edge("server2","face")
workflow.add_edge(["license_node", "face"], "dispatch")
workflow.add_edge("server2", "service_identify")
workflow.add_edge("service_identify","dispatch")
workflow.add_edge("dispatch", END)

app = workflow.compile()

# ==========================================
# TEST EXECUTION
# ==========================================
if __name__ == "__main__":
    TEST_IMAGE_PATH = "./images/image.png" 
    
    try:
        with open(TEST_IMAGE_PATH, "rb") as f:
            image_bytes = f.read()

        test_input = {
            "img_id": "TEST_EVENT_001",
            "camera_id": "CAM_KOCHI_01",
            "timestamp": "2026-02-27 14:15:00",
            "geolocation": {"lat": 9.9312, "lon": 76.2673},
            "frame": image_bytes,
            "hazards": [],
            "status": "Starting",
            "license_plates":[],
            "face_detected":[]
        }

        print("--- INVOKING LANGGRAPH ---")
        final_state = app.invoke(test_input)

        print("\n--- FINAL GRAPH STATE ---")
        print(f"Status: {final_state['status']}")
        print(f"Hazards Detected: {final_state['hazards']}")
        # try:
        #     png_data = app.get_graph().draw_mermaid_png()
            
        #     # 2. Open a file in 'wb' (write binary) mode and save it
        #     with open("incident_workflow.png", "wb") as f:
        #         f.write(png_data)
                
        #     print("✅ Workflow saved to: incident_workflow.png")
        # except Exception as e:
        #     print(f"❌ Failed to save PNG. Ensure you have 'pygraphviz' or 'grandalf' installed. Error: {e}")
        
    except FileNotFoundError:
        print(f"❌ ERROR: Could not find {TEST_IMAGE_PATH}. Please put an image in the folder.")