# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: accident.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'accident.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63\x63ident.proto\x12\x08\x61\x63\x63ident\"h\n\x0c\x41\x63\x63identData\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x11\n\tcamera_id\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t2K\n\x10\x41\x63\x63identReporter\x12\x37\n\tSendAlert\x12\x16.accident.AccidentData\x1a\x12.accident.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accident_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCIDENTDATA']._serialized_start=28
  _globals['_ACCIDENTDATA']._serialized_end=132
  _globals['_RESPONSE']._serialized_start=134
  _globals['_RESPONSE']._serialized_end=160
  _globals['_ACCIDENTREPORTER']._serialized_start=162
  _globals['_ACCIDENTREPORTER']._serialized_end=237
# @@protoc_insertion_point(module_scope)
